import type { FoundationKnowledgeEdge, FoundationKnowledgeNode } from '../domain/types.js';

const topologyCardStyle = 'luminous scientific atlas, crisp Chinese labels, high contrast, structured visual hierarchy, concept graph topology';

export const SEEDED_FOUNDATION_KNOWLEDGE_NODES: FoundationKnowledgeNode[] = [
  {
    key: 'physics.classical_mechanics',
    label: '经典力学',
    domain: 'physics',
    domainLayer: 'foundation-science',
    scale: 'module',
    summary: '研究物体运动、力和因果模型，是理解宏观世界的第一套可计算语言。',
    coreQuestion: '力如何改变运动？',
    prerequisites: [],
    relatedCurriculumNodes: ['ma-g8-geom-midpoint'],
    relatedMistakePatterns: ['strategy-selection', 'concept-confusion'],
    keywords: ['运动', '力', '牛顿定律', '因果', '模型'],
    mediaPromptSeed: {
      visualMetaphor: '轨道网格上的小球被力箭头推动，运动路径逐帧显现',
      gptImageStyle: topologyCardStyle,
      seedanceStoryboard: [
        '第一格：全局物理地图中经典力学节点亮起。',
        '第二格：力箭头推动小球，运动轨迹从静止变成加速。',
        '第三格：把力和运动连接到课内几何/函数中的变化关系。',
      ],
    },
  },
  {
    key: 'physics.electromagnetism',
    label: '电磁学',
    domain: 'physics',
    domainLayer: 'foundation-science',
    scale: 'module',
    summary: '研究电场、磁场、电荷、电流和光的统一关系。',
    coreQuestion: '电场、磁场和光如何统一？',
    prerequisites: ['physics.classical_mechanics'],
    relatedCurriculumNodes: [],
    relatedMistakePatterns: ['rule-recall', 'concept-confusion'],
    keywords: ['电场', '磁场', '电流', '电磁波', '麦克斯韦方程'],
    mediaPromptSeed: {
      visualMetaphor: '电荷周围的场线与波形互相转化',
      gptImageStyle: topologyCardStyle,
      seedanceStoryboard: [
        '第一格：电场线从电荷发散，磁场线环绕电流。',
        '第二格：变化的电场和磁场互相激发，形成光波。',
        '第三格：把看不见的场转成学生可操作的方向判断任务。',
      ],
    },
  },
  {
    key: 'physics.thermo_stat',
    label: '热力学与统计物理',
    domain: 'physics',
    domainLayer: 'foundation-science',
    scale: 'module',
    summary: '从大量粒子的微观运动中解释温度、能量、熵和宏观规律。',
    coreQuestion: '大量粒子的整体规律如何出现？',
    prerequisites: ['physics.classical_mechanics'],
    relatedCurriculumNodes: [],
    relatedMistakePatterns: ['concept-confusion'],
    keywords: ['温度', '能量', '熵', '统计', '概率', '涌现'],
    mediaPromptSeed: {
      visualMetaphor: '无数粒子碰撞后形成平滑的温度曲线',
      gptImageStyle: topologyCardStyle,
      seedanceStoryboard: [
        '第一格：微观粒子混乱运动。',
        '第二格：镜头拉远，混乱变成温度和分布曲线。',
        '第三格：学生选择微观随机与宏观规律之间的正确关系。',
      ],
    },
  },
  {
    key: 'physics.relativity',
    label: '相对论',
    domain: 'physics',
    domainLayer: 'foundation-science',
    scale: 'module',
    summary: '重写时间、空间、速度和引力的关系，建立现代时空观。',
    coreQuestion: '时间、空间和引力如何重写？',
    prerequisites: ['physics.classical_mechanics', 'physics.electromagnetism'],
    relatedCurriculumNodes: [],
    relatedMistakePatterns: ['concept-confusion'],
    keywords: ['参考系', '光速', '时空', '引力', '曲率'],
    mediaPromptSeed: {
      visualMetaphor: '光束穿过弯曲网格，时钟在不同路径上不同步',
      gptImageStyle: topologyCardStyle,
      seedanceStoryboard: [
        '第一格：不同参考系的观察者看到同一束光。',
        '第二格：时空网格被质量压弯。',
        '第三格：学生判断哪些量依赖参考系，哪些规律保持一致。',
      ],
    },
  },
  {
    key: 'physics.quantum',
    label: '量子力学',
    domain: 'physics',
    domainLayer: 'foundation-science',
    scale: 'module',
    summary: '描述微观世界中的波函数、叠加、不确定性和测量。',
    coreQuestion: '微观世界为什么不能按直觉运行？',
    prerequisites: ['physics.classical_mechanics'],
    relatedCurriculumNodes: [],
    relatedMistakePatterns: ['concept-confusion', 'guessing-with-low-monitoring'],
    keywords: ['波函数', '叠加', '不确定性', '测量', '原子'],
    mediaPromptSeed: {
      visualMetaphor: '电子轨道从确定小球变成概率云',
      gptImageStyle: topologyCardStyle,
      seedanceStoryboard: [
        '第一格：学生以为电子像小球沿轨道运动。',
        '第二格：画面切换成概率云和波函数。',
        '第三格：测量动作让一个可能性被选中。',
      ],
    },
  },
  {
    key: 'physics.qft_particle',
    label: '量子场论与粒子物理',
    domain: 'physics',
    domainLayer: 'foundation-science',
    scale: 'module',
    summary: '把粒子理解为场的激发，解释基本粒子和相互作用。',
    coreQuestion: '基本粒子和相互作用从哪里来？',
    prerequisites: ['physics.quantum', 'physics.relativity'],
    relatedCurriculumNodes: [],
    relatedMistakePatterns: ['concept-confusion'],
    keywords: ['场', '粒子', '标准模型', '相互作用', '夸克'],
    mediaPromptSeed: {
      visualMetaphor: '场的网格被拨动后出现粒子亮点',
      gptImageStyle: topologyCardStyle,
      seedanceStoryboard: [
        '第一格：空旷空间显示为一张可振动的场网格。',
        '第二格：局部激发变成粒子。',
        '第三格：不同颜色的连线表示相互作用。',
      ],
    },
  },
  {
    key: 'physics.symmetry_conservation',
    label: '对称性与守恒律',
    domain: 'physics',
    domainLayer: 'foundation-science',
    scale: 'module',
    summary: '用对称性解释为什么能量、动量、电荷等量会守恒。',
    coreQuestion: '为什么守恒是规律的核心？',
    prerequisites: ['physics.classical_mechanics'],
    relatedCurriculumNodes: ['ma-g8-function-quadratic-vertex'],
    relatedMistakePatterns: ['rule-recall', 'strategy-selection'],
    keywords: ['对称性', '守恒', '能量', '动量', '约束'],
    mediaPromptSeed: {
      visualMetaphor: '宇宙账本左右两栏保持平衡，变换后总量不变',
      gptImageStyle: topologyCardStyle,
      seedanceStoryboard: [
        '第一格：物理地图底部守恒律节点亮起。',
        '第二格：系统变化但能量账本总数不变。',
        '第三格：连接到数学等式平衡和解题约束。',
      ],
    },
  },
  {
    key: 'physics.spacetime_cosmos',
    label: '时空与宇宙学',
    domain: 'physics',
    domainLayer: 'foundation-science',
    scale: 'module',
    summary: '研究宇宙的大尺度结构、演化、暗物质、暗能量和星系形成。',
    coreQuestion: '宇宙的大尺度结构如何演化？',
    prerequisites: ['physics.relativity', 'physics.thermo_stat'],
    relatedCurriculumNodes: [],
    relatedMistakePatterns: ['concept-confusion'],
    keywords: ['宇宙', '星系', '暗物质', '膨胀', '时空结构'],
    mediaPromptSeed: {
      visualMetaphor: '星系网络在膨胀网格上生长',
      gptImageStyle: topologyCardStyle,
      seedanceStoryboard: [
        '第一格：时空网格向外扩展。',
        '第二格：星系沿大尺度网络聚集。',
        '第三格：学生区分宇宙膨胀和物体在空间中飞散。',
      ],
    },
  },
  {
    key: 'physics.complexity_frontier',
    label: '复杂系统与前沿统一',
    domain: 'physics',
    domainLayer: 'foundation-science',
    scale: 'module',
    summary: '研究非线性、混沌、涌现和统一理论，解释复杂现象如何从简单规则中出现。',
    coreQuestion: '简单规则如何产生复杂现象？',
    prerequisites: ['physics.thermo_stat', 'physics.symmetry_conservation'],
    relatedCurriculumNodes: [],
    relatedMistakePatterns: ['strategy-selection', 'knowledge-fragile'],
    keywords: ['复杂系统', '非线性', '混沌', '涌现', '统一'],
    mediaPromptSeed: {
      visualMetaphor: '简单局部规则生成旋涡、网络和群体图案',
      gptImageStyle: topologyCardStyle,
      seedanceStoryboard: [
        '第一格：几个简单规则按钮被依次点亮。',
        '第二格：局部互动生成复杂旋涡图案。',
        '第三格：学生判断复杂结果背后的简单规则。',
      ],
    },
  },
  {
    key: 'neuroscience.neuron_bioelectricity',
    label: '神经元与膜电生理',
    domain: 'neuroscience',
    domainLayer: 'foundation-science',
    scale: 'module',
    summary: '解释神经元如何通过膜电位、动作电位和离子通道产生信号。',
    coreQuestion: '神经信号如何产生？',
    prerequisites: [],
    relatedCurriculumNodes: [],
    relatedMistakePatterns: ['cue-missed', 'knowledge-fragile'],
    keywords: ['神经元', '膜电位', '动作电位', '离子通道', '电信号'],
    mediaPromptSeed: {
      visualMetaphor: '电信号沿神经元轴突像光脉冲一样传播',
      gptImageStyle: topologyCardStyle,
      seedanceStoryboard: [
        '第一格：神经元静息，膜内外电荷分布清晰。',
        '第二格：动作电位像光波沿轴突传播。',
        '第三格：连接到学生读题时注意信号被启动。',
      ],
    },
  },
  {
    key: 'neuroscience.synapse_transmitter',
    label: '突触与神经递质',
    domain: 'neuroscience',
    domainLayer: 'foundation-science',
    scale: 'module',
    summary: '解释神经元之间如何通过化学递质和受体传递、调节和塑造信息。',
    coreQuestion: '神经元如何传递信息？',
    prerequisites: ['neuroscience.neuron_bioelectricity'],
    relatedCurriculumNodes: [],
    relatedMistakePatterns: ['rule-not-triggered', 'knowledge-fragile'],
    keywords: ['突触', '神经递质', '受体', '多巴胺', 'GABA'],
    mediaPromptSeed: {
      visualMetaphor: '突触小泡释放发光递质，受体像锁一样被打开',
      gptImageStyle: topologyCardStyle,
      seedanceStoryboard: [
        '第一格：电信号到达突触末端。',
        '第二格：递质释放并结合受体。',
        '第三格：连接到奖励反馈如何加强下一次行动。',
      ],
    },
  },
  {
    key: 'neuroscience.circuit',
    label: '神经回路',
    domain: 'neuroscience',
    domainLayer: 'foundation-science',
    scale: 'module',
    summary: '解释兴奋、抑制、反馈和前馈连接如何构成可执行的行为回路。',
    coreQuestion: '简单连接如何形成行为？',
    prerequisites: ['neuroscience.synapse_transmitter'],
    relatedCurriculumNodes: [],
    relatedMistakePatterns: ['strategy-selection', 'guessing-with-low-monitoring'],
    keywords: ['回路', '兴奋', '抑制', '反馈', '前馈'],
    mediaPromptSeed: {
      visualMetaphor: '绿色兴奋节点和橙色抑制节点组成可切换回路',
      gptImageStyle: topologyCardStyle,
      seedanceStoryboard: [
        '第一格：三个神经元连接成小回路。',
        '第二格：兴奋与抑制信号改变输出。',
        '第三格：映射到学生先触发规则再行动的学习回路。',
      ],
    },
  },
  {
    key: 'neuroscience.brain_systems',
    label: '脑区与系统',
    domain: 'neuroscience',
    domainLayer: 'foundation-science',
    scale: 'module',
    summary: '解释皮层、丘脑、海马、基底节、小脑和脑干如何协作。',
    coreQuestion: '不同脑区如何协作？',
    prerequisites: ['neuroscience.circuit'],
    relatedCurriculumNodes: [],
    relatedMistakePatterns: ['concept-confusion'],
    keywords: ['脑区', '皮层', '海马', '基底节', '小脑', '协作'],
    mediaPromptSeed: {
      visualMetaphor: '半透明大脑中不同脑区像城市交通系统协同亮起',
      gptImageStyle: topologyCardStyle,
      seedanceStoryboard: [
        '第一格：大脑地图展示主要脑区。',
        '第二格：记忆、动作和决策通路依次亮起。',
        '第三格：学生把学习任务匹配到对应脑区功能。',
      ],
    },
  },
  {
    key: 'neuroscience.sensation_motion',
    label: '感觉与运动',
    domain: 'neuroscience',
    domainLayer: 'foundation-science',
    scale: 'module',
    summary: '解释感觉输入如何被编码、整合，并转化为运动输出和行动闭环。',
    coreQuestion: '输入如何变成行动？',
    prerequisites: ['neuroscience.brain_systems'],
    relatedCurriculumNodes: [],
    relatedMistakePatterns: ['cue-missed', 'strategy-selection'],
    keywords: ['感觉', '运动', '编码', '行动', '闭环'],
    mediaPromptSeed: {
      visualMetaphor: '眼睛、耳朵、手部动作和脑区之间形成闭环箭头',
      gptImageStyle: topologyCardStyle,
      seedanceStoryboard: [
        '第一格：题目信息作为感觉输入进入系统。',
        '第二格：大脑选择关键线索并规划动作。',
        '第三格：学生执行拖拽或画线动作完成闭环。',
      ],
    },
  },
  {
    key: 'neuroscience.learning_memory',
    label: '学习与记忆',
    domain: 'neuroscience',
    domainLayer: 'foundation-science',
    scale: 'module',
    summary: '解释突触可塑性、工作记忆、长期记忆和提取练习如何支持学习。',
    coreQuestion: '知识如何被巩固和提取？',
    prerequisites: ['neuroscience.synapse_transmitter', 'neuroscience.brain_systems'],
    relatedCurriculumNodes: ['en-g4-grammar-there-be', 'zh-g4-phonetic-polyphone'],
    relatedMistakePatterns: ['rule-recall', 'knowledge-fragile'],
    keywords: ['学习', '记忆', 'LTP', '工作记忆', '复习', '提取'],
    mediaPromptSeed: {
      visualMetaphor: '海马回路中路径被重复点亮后变成稳定通道',
      gptImageStyle: topologyCardStyle,
      seedanceStoryboard: [
        '第一格：新知识只是一条微弱连接。',
        '第二格：重复提取让连接变亮变粗。',
        '第三格：连接到错题重做和间隔复习任务。',
      ],
    },
  },
  {
    key: 'neuroscience.development_plasticity',
    label: '发育与可塑性',
    domain: 'neuroscience',
    domainLayer: 'foundation-science',
    scale: 'module',
    summary: '解释神经发育、关键期、突触修剪和训练如何改变大脑网络。',
    coreQuestion: '大脑如何随训练改变？',
    prerequisites: ['neuroscience.learning_memory'],
    relatedCurriculumNodes: [],
    relatedMistakePatterns: ['knowledge-fragile'],
    keywords: ['发育', '可塑性', '关键期', '突触修剪', '训练'],
    mediaPromptSeed: {
      visualMetaphor: '树状神经网络从稀疏到修剪再到强化',
      gptImageStyle: topologyCardStyle,
      seedanceStoryboard: [
        '第一格：早期神经连接快速生长。',
        '第二格：不用的连接淡出，常用通路增强。',
        '第三格：把长期练习解释为可塑性改造。',
      ],
    },
  },
  {
    key: 'neuroscience.cognition_consciousness',
    label: '认知与意识',
    domain: 'neuroscience',
    domainLayer: 'foundation-science',
    scale: 'module',
    summary: '解释注意、决策、情绪、意识和执行功能如何影响学习表现。',
    coreQuestion: '注意、决策和意识如何工作？',
    prerequisites: ['neuroscience.brain_systems', 'neuroscience.learning_memory'],
    relatedCurriculumNodes: [],
    relatedMistakePatterns: ['guessing-with-low-monitoring', 'cue-missed'],
    keywords: ['注意', '决策', '意识', '执行功能', '元认知'],
    mediaPromptSeed: {
      visualMetaphor: '脑内聚光灯照亮关键信号，噪声节点逐渐变暗',
      gptImageStyle: topologyCardStyle,
      seedanceStoryboard: [
        '第一格：题面中信号和噪声同时出现。',
        '第二格：注意聚光灯锁定关键条件。',
        '第三格：学生自检是否先触发规则再作答。',
      ],
    },
  },
  {
    key: 'neuroscience.computational_bci',
    label: '计算神经科学与脑机前沿',
    domain: 'neuroscience',
    domainLayer: 'foundation-science',
    scale: 'module',
    summary: '用模型、编码、网络动力学和接口理解大脑，并连接 AI 与脑机未来。',
    coreQuestion: '脑如何被建模和接口化？',
    prerequisites: ['neuroscience.circuit', 'neuroscience.cognition_consciousness'],
    relatedCurriculumNodes: [],
    relatedMistakePatterns: ['strategy-selection'],
    keywords: ['计算神经科学', '神经编码', '网络动力学', '预测', '脑机接口', 'AI'],
    mediaPromptSeed: {
      visualMetaphor: '脑网络和芯片网络通过信号桥连接',
      gptImageStyle: topologyCardStyle,
      seedanceStoryboard: [
        '第一格：神经活动被转化成信号轨迹。',
        '第二格：模型预测下一次行动。',
        '第三格：连接到 AI Active 如何读状态并调度学习动作。',
      ],
    },
  },
];

export const SEEDED_FOUNDATION_KNOWLEDGE_EDGES: FoundationKnowledgeEdge[] = [
  {
    source: 'physics.classical_mechanics',
    target: 'physics.symmetry_conservation',
    kind: 'explains',
    rationale: '经典力学中的能量和动量守恒为守恒律提供最直观入口。',
  },
  {
    source: 'physics.electromagnetism',
    target: 'physics.relativity',
    kind: 'prerequisite',
    rationale: '电磁学中的光速不变问题推动相对论时空观。',
  },
  {
    source: 'physics.quantum',
    target: 'physics.qft_particle',
    kind: 'prerequisite',
    rationale: '量子场论建立在量子力学与相对论的共同基础上。',
  },
  {
    source: 'physics.thermo_stat',
    target: 'physics.complexity_frontier',
    kind: 'explains',
    rationale: '统计物理提供从微观互动到宏观涌现的桥梁。',
  },
  {
    source: 'physics.symmetry_conservation',
    target: 'ma-g8-function-quadratic-vertex',
    kind: 'maps-to-curriculum',
    rationale: '对称性思想可连接到函数图像、对称轴和约束条件。',
  },
  {
    source: 'neuroscience.neuron_bioelectricity',
    target: 'neuroscience.synapse_transmitter',
    kind: 'prerequisite',
    rationale: '神经元电信号到达突触后转化为化学传递。',
  },
  {
    source: 'neuroscience.synapse_transmitter',
    target: 'neuroscience.learning_memory',
    kind: 'explains',
    rationale: '突触可塑性是记忆巩固的重要机制。',
  },
  {
    source: 'neuroscience.cognition_consciousness',
    target: 'ai_active.signal_noise_ratio',
    kind: 'supports-cognition',
    rationale: '注意选择和执行控制解释规则信号与题面噪声的分离。',
  },
  {
    source: 'neuroscience.learning_memory',
    target: 'en-g4-grammar-there-be',
    kind: 'maps-to-curriculum',
    rationale: '规则召回和提取练习可解释 there be 就近一致的巩固方式。',
  },
  {
    source: 'physics.thermo_stat',
    target: 'neuroscience.circuit',
    kind: 'analogy',
    rationale: '大量粒子的统计规律可类比大量神经元活动产生稳定输出。',
  },
];
