export interface SmsOtpMessage {
  /** E.164-ish phone number as delivered by Supabase, e.g. "8613800138000". */
  phone: string;
  /** One-time passcode generated by Supabase Auth. */
  otp: string;
}

export interface SmsSender {
  sendOtp(message: SmsOtpMessage): Promise<void>;
}

/**
 * Default SMS sender used until a real provider is configured.
 * It never sends anything; it only records the last message so tests and
 * controlled demo deployments can assert behaviour without a live gateway.
 * Mirrors the stub-by-default idiom used for video (StubSeedanceClient).
 */
export class StubSmsSender implements SmsSender {
  public lastMessage: SmsOtpMessage | null = null;

  async sendOtp(message: SmsOtpMessage): Promise<void> {
    this.lastMessage = message;
  }
}
